services:
  api-passin:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres/passin
      - API_BASE_URL=http://localhost:3333
    depends_on:
      - postgres
    networks:
      - passin
  
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passin
    networks:
      - passin
    volumes:
      - db:/var/lib/postgresql/data

networks:
  passin:
    driver: bridge

volumes:
  db: